/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Workspace.Model
{
    /// <summary>
    /// SendUserEventDataData
    /// </summary>
    [DataContract]
    public partial class SendUserEventDataData :  IEquatable<SendUserEventDataData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendUserEventDataData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendUserEventDataData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendUserEventDataData" /> class.
        /// </summary>
        /// <param name="UserData">UserData (required).</param>
        /// <param name="CallUuid">CallUuid.</param>
        public SendUserEventDataData(List<Kvpair> UserData = default(List<Kvpair>), string CallUuid = default(string))
        {
            // to ensure "UserData" is required (not null)
            if (UserData == null)
            {
                throw new InvalidDataException("UserData is a required property for SendUserEventDataData and cannot be null");
            }
            else
            {
                this.UserData = UserData;
            }
            this.CallUuid = CallUuid;
        }
        
        /// <summary>
        /// Gets or Sets UserData
        /// </summary>
        [DataMember(Name="userData", EmitDefaultValue=false)]
        public List<Kvpair> UserData { get; set; }

        /// <summary>
        /// Gets or Sets CallUuid
        /// </summary>
        [DataMember(Name="callUuid", EmitDefaultValue=false)]
        public string CallUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SendUserEventDataData {\n");
            sb.Append("  UserData: ").Append(UserData).Append("\n");
            sb.Append("  CallUuid: ").Append(CallUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SendUserEventDataData);
        }

        /// <summary>
        /// Returns true if SendUserEventDataData instances are equal
        /// </summary>
        /// <param name="other">Instance of SendUserEventDataData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SendUserEventDataData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.UserData == other.UserData ||
                    this.UserData != null &&
                    this.UserData.SequenceEqual(other.UserData)
                ) && 
                (
                    this.CallUuid == other.CallUuid ||
                    this.CallUuid != null &&
                    this.CallUuid.Equals(other.CallUuid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.UserData != null)
                    hash = hash * 59 + this.UserData.GetHashCode();
                if (this.CallUuid != null)
                    hash = hash * 59 + this.CallUuid.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
