/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Workspace.Model
{
    /// <summary>
    /// TargetsrecentsaddData
    /// </summary>
    [DataContract]
    public partial class TargetsrecentsaddData :  IEquatable<TargetsrecentsaddData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TargetsrecentsaddData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TargetsrecentsaddData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TargetsrecentsaddData" /> class.
        /// </summary>
        /// <param name="Target">The recent target (required).</param>
        /// <param name="RecentInformation">data about recent interaction with the target (required).</param>
        public TargetsrecentsaddData(TargetInformation Target = default(TargetInformation), RecentData RecentInformation = default(RecentData))
        {
            // to ensure "Target" is required (not null)
            if (Target == null)
            {
                throw new InvalidDataException("Target is a required property for TargetsrecentsaddData and cannot be null");
            }
            else
            {
                this.Target = Target;
            }
            // to ensure "RecentInformation" is required (not null)
            if (RecentInformation == null)
            {
                throw new InvalidDataException("RecentInformation is a required property for TargetsrecentsaddData and cannot be null");
            }
            else
            {
                this.RecentInformation = RecentInformation;
            }
        }
        
        /// <summary>
        /// The recent target
        /// </summary>
        /// <value>The recent target</value>
        [DataMember(Name="target", EmitDefaultValue=false)]
        public TargetInformation Target { get; set; }

        /// <summary>
        /// data about recent interaction with the target
        /// </summary>
        /// <value>data about recent interaction with the target</value>
        [DataMember(Name="recentInformation", EmitDefaultValue=false)]
        public RecentData RecentInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TargetsrecentsaddData {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  RecentInformation: ").Append(RecentInformation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TargetsrecentsaddData);
        }

        /// <summary>
        /// Returns true if TargetsrecentsaddData instances are equal
        /// </summary>
        /// <param name="other">Instance of TargetsrecentsaddData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TargetsrecentsaddData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Target == other.Target ||
                    this.Target != null &&
                    this.Target.Equals(other.Target)
                ) && 
                (
                    this.RecentInformation == other.RecentInformation ||
                    this.RecentInformation != null &&
                    this.RecentInformation.Equals(other.RecentInformation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Target != null)
                    hash = hash * 59 + this.Target.GetHashCode();
                if (this.RecentInformation != null)
                    hash = hash * 59 + this.RecentInformation.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
