/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Workspace.Model
{
    /// <summary>
    /// VoicesetforwardData
    /// </summary>
    [DataContract]
    public partial class VoicesetforwardData :  IEquatable<VoicesetforwardData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VoicesetforwardData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VoicesetforwardData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VoicesetforwardData" /> class.
        /// </summary>
        /// <param name="ForwardTo">ForwardTo (required).</param>
        public VoicesetforwardData(string ForwardTo = default(string))
        {
            // to ensure "ForwardTo" is required (not null)
            if (ForwardTo == null)
            {
                throw new InvalidDataException("ForwardTo is a required property for VoicesetforwardData and cannot be null");
            }
            else
            {
                this.ForwardTo = ForwardTo;
            }
        }
        
        /// <summary>
        /// Gets or Sets ForwardTo
        /// </summary>
        [DataMember(Name="forwardTo", EmitDefaultValue=false)]
        public string ForwardTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VoicesetforwardData {\n");
            sb.Append("  ForwardTo: ").Append(ForwardTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as VoicesetforwardData);
        }

        /// <summary>
        /// Returns true if VoicesetforwardData instances are equal
        /// </summary>
        /// <param name="other">Instance of VoicesetforwardData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VoicesetforwardData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ForwardTo == other.ForwardTo ||
                    this.ForwardTo != null &&
                    this.ForwardTo.Equals(other.ForwardTo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ForwardTo != null)
                    hash = hash * 59 + this.ForwardTo.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
