/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Workspace.Model
{
    /// <summary>
    /// VoicenotreadyData
    /// </summary>
    [DataContract]
    public partial class VoicenotreadyData :  IEquatable<VoicenotreadyData>, IValidatableObject
    {
        /// <summary>
        /// the agent workmode.
        /// </summary>
        /// <value>the agent workmode.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AgentWorkModeEnum
        {
            
            /// <summary>
            /// Enum AfterCallWork for "AfterCallWork"
            /// </summary>
            [EnumMember(Value = "AfterCallWork")]
            AfterCallWork,
            
            /// <summary>
            /// Enum AuxWork for "AuxWork"
            /// </summary>
            [EnumMember(Value = "AuxWork")]
            AuxWork,
            
            /// <summary>
            /// Enum LegalGuard for "LegalGuard"
            /// </summary>
            [EnumMember(Value = "LegalGuard")]
            LegalGuard,
            
            /// <summary>
            /// Enum NoCallDisconnect for "NoCallDisconnect"
            /// </summary>
            [EnumMember(Value = "NoCallDisconnect")]
            NoCallDisconnect,
            
            /// <summary>
            /// Enum WalkAway for "WalkAway"
            /// </summary>
            [EnumMember(Value = "WalkAway")]
            WalkAway
        }

        /// <summary>
        /// the agent workmode.
        /// </summary>
        /// <value>the agent workmode.</value>
        [DataMember(Name="agentWorkMode", EmitDefaultValue=false)]
        public AgentWorkModeEnum? AgentWorkMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VoicenotreadyData" /> class.
        /// </summary>
        /// <param name="ReasonCode">the reason code.</param>
        /// <param name="AgentWorkMode">the agent workmode..</param>
        /// <param name="Reasons">A key/value pairs list of a data structure that provides additional information associated with this action..</param>
        /// <param name="Extensions">A key/value pairs list of additional data..</param>
        public VoicenotreadyData(string ReasonCode = default(string), AgentWorkModeEnum? AgentWorkMode = default(AgentWorkModeEnum?), List<Kvpair> Reasons = default(List<Kvpair>), List<Kvpair> Extensions = default(List<Kvpair>))
        {
            this.ReasonCode = ReasonCode;
            this.AgentWorkMode = AgentWorkMode;
            this.Reasons = Reasons;
            this.Extensions = Extensions;
        }
        
        /// <summary>
        /// the reason code
        /// </summary>
        /// <value>the reason code</value>
        [DataMember(Name="reasonCode", EmitDefaultValue=false)]
        public string ReasonCode { get; set; }


        /// <summary>
        /// A key/value pairs list of a data structure that provides additional information associated with this action.
        /// </summary>
        /// <value>A key/value pairs list of a data structure that provides additional information associated with this action.</value>
        [DataMember(Name="reasons", EmitDefaultValue=false)]
        public List<Kvpair> Reasons { get; set; }

        /// <summary>
        /// A key/value pairs list of additional data.
        /// </summary>
        /// <value>A key/value pairs list of additional data.</value>
        [DataMember(Name="extensions", EmitDefaultValue=false)]
        public List<Kvpair> Extensions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VoicenotreadyData {\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("  AgentWorkMode: ").Append(AgentWorkMode).Append("\n");
            sb.Append("  Reasons: ").Append(Reasons).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as VoicenotreadyData);
        }

        /// <summary>
        /// Returns true if VoicenotreadyData instances are equal
        /// </summary>
        /// <param name="other">Instance of VoicenotreadyData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VoicenotreadyData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ReasonCode == other.ReasonCode ||
                    this.ReasonCode != null &&
                    this.ReasonCode.Equals(other.ReasonCode)
                ) && 
                (
                    this.AgentWorkMode == other.AgentWorkMode ||
                    this.AgentWorkMode != null &&
                    this.AgentWorkMode.Equals(other.AgentWorkMode)
                ) && 
                (
                    this.Reasons == other.Reasons ||
                    this.Reasons != null &&
                    this.Reasons.SequenceEqual(other.Reasons)
                ) && 
                (
                    this.Extensions == other.Extensions ||
                    this.Extensions != null &&
                    this.Extensions.SequenceEqual(other.Extensions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ReasonCode != null)
                    hash = hash * 59 + this.ReasonCode.GetHashCode();
                if (this.AgentWorkMode != null)
                    hash = hash * 59 + this.AgentWorkMode.GetHashCode();
                if (this.Reasons != null)
                    hash = hash * 59 + this.Reasons.GetHashCode();
                if (this.Extensions != null)
                    hash = hash * 59 + this.Extensions.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
