/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Genesys.Workspace.Client;
using Genesys.Workspace.Model;

namespace Genesys.Workspace.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITargetsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Ack the missed calls in recent target
        /// </summary>
        /// <remarks>
        /// Ack the missed calls in recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiSuccessResponse</returns>
        ApiSuccessResponse AckRecentMissedCalls ();

        /// <summary>
        /// Ack the missed calls in recent target
        /// </summary>
        /// <remarks>
        /// Ack the missed calls in recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        ApiResponse<ApiSuccessResponse> AckRecentMissedCallsWithHttpInfo ();
        /// <summary>
        /// Add a recent target
        /// </summary>
        /// <remarks>
        /// Add a recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>ApiSuccessResponse</returns>
        ApiSuccessResponse AddRecentTarget (RecentTargetData recentTargetData);

        /// <summary>
        /// Add a recent target
        /// </summary>
        /// <remarks>
        /// Add a recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        ApiResponse<ApiSuccessResponse> AddRecentTargetWithHttpInfo (RecentTargetData recentTargetData);
        /// <summary>
        /// delete a personal favorite
        /// </summary>
        /// <remarks>
        /// delete a personal favorite by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiSuccessResponse</returns>
        ApiSuccessResponse DeletePersonalFavorite (string id, string type);

        /// <summary>
        /// delete a personal favorite
        /// </summary>
        /// <remarks>
        /// delete a personal favorite by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        ApiResponse<ApiSuccessResponse> DeletePersonalFavoriteWithHttpInfo (string id, string type);
        /// <summary>
        /// Search for targets
        /// </summary>
        /// <remarks>
        /// Search for targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>TargetsResponse</returns>
        TargetsResponse Get (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null);

        /// <summary>
        /// Search for targets
        /// </summary>
        /// <remarks>
        /// Search for targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        ApiResponse<TargetsResponse> GetWithHttpInfo (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null);
        /// <summary>
        /// Get personal favorites
        /// </summary>
        /// <remarks>
        /// Get personal favorites
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>TargetsResponse</returns>
        TargetsResponse GetPersonalFavorites (decimal? limit = null);

        /// <summary>
        /// Get personal favorites
        /// </summary>
        /// <remarks>
        /// Get personal favorites
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        ApiResponse<TargetsResponse> GetPersonalFavoritesWithHttpInfo (decimal? limit = null);
        /// <summary>
        /// Get recent targets
        /// </summary>
        /// <remarks>
        /// Get recent targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>TargetsResponse</returns>
        TargetsResponse GetRecentTargets (decimal? limit = null);

        /// <summary>
        /// Get recent targets
        /// </summary>
        /// <remarks>
        /// Get recent targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        ApiResponse<TargetsResponse> GetRecentTargetsWithHttpInfo (decimal? limit = null);
        /// <summary>
        /// Get a target
        /// </summary>
        /// <remarks>
        /// Get a specific target by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>TargetsResponse</returns>
        TargetsResponse GetTarget (decimal? id, string type);

        /// <summary>
        /// Get a target
        /// </summary>
        /// <remarks>
        /// Get a specific target by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        ApiResponse<TargetsResponse> GetTargetWithHttpInfo (decimal? id, string type);
        /// <summary>
        /// Save a personal favorite
        /// </summary>
        /// <remarks>
        /// Save a personal favorite
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>ApiSuccessResponse</returns>
        ApiSuccessResponse SavePersonalFavorite (PersonalFavoriteData personalFavoriteData);

        /// <summary>
        /// Save a personal favorite
        /// </summary>
        /// <remarks>
        /// Save a personal favorite
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        ApiResponse<ApiSuccessResponse> SavePersonalFavoriteWithHttpInfo (PersonalFavoriteData personalFavoriteData);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Ack the missed calls in recent target
        /// </summary>
        /// <remarks>
        /// Ack the missed calls in recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiSuccessResponse</returns>
        System.Threading.Tasks.Task<ApiSuccessResponse> AckRecentMissedCallsAsync ();

        /// <summary>
        /// Ack the missed calls in recent target
        /// </summary>
        /// <remarks>
        /// Ack the missed calls in recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> AckRecentMissedCallsAsyncWithHttpInfo ();
        /// <summary>
        /// Add a recent target
        /// </summary>
        /// <remarks>
        /// Add a recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>Task of ApiSuccessResponse</returns>
        System.Threading.Tasks.Task<ApiSuccessResponse> AddRecentTargetAsync (RecentTargetData recentTargetData);

        /// <summary>
        /// Add a recent target
        /// </summary>
        /// <remarks>
        /// Add a recent target
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> AddRecentTargetAsyncWithHttpInfo (RecentTargetData recentTargetData);
        /// <summary>
        /// delete a personal favorite
        /// </summary>
        /// <remarks>
        /// delete a personal favorite by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiSuccessResponse</returns>
        System.Threading.Tasks.Task<ApiSuccessResponse> DeletePersonalFavoriteAsync (string id, string type);

        /// <summary>
        /// delete a personal favorite
        /// </summary>
        /// <remarks>
        /// delete a personal favorite by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> DeletePersonalFavoriteAsyncWithHttpInfo (string id, string type);
        /// <summary>
        /// Search for targets
        /// </summary>
        /// <remarks>
        /// Search for targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        System.Threading.Tasks.Task<TargetsResponse> GetAsync (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null);

        /// <summary>
        /// Search for targets
        /// </summary>
        /// <remarks>
        /// Search for targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetAsyncWithHttpInfo (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null);
        /// <summary>
        /// Get personal favorites
        /// </summary>
        /// <remarks>
        /// Get personal favorites
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        System.Threading.Tasks.Task<TargetsResponse> GetPersonalFavoritesAsync (decimal? limit = null);

        /// <summary>
        /// Get personal favorites
        /// </summary>
        /// <remarks>
        /// Get personal favorites
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetPersonalFavoritesAsyncWithHttpInfo (decimal? limit = null);
        /// <summary>
        /// Get recent targets
        /// </summary>
        /// <remarks>
        /// Get recent targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        System.Threading.Tasks.Task<TargetsResponse> GetRecentTargetsAsync (decimal? limit = null);

        /// <summary>
        /// Get recent targets
        /// </summary>
        /// <remarks>
        /// Get recent targets
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetRecentTargetsAsyncWithHttpInfo (decimal? limit = null);
        /// <summary>
        /// Get a target
        /// </summary>
        /// <remarks>
        /// Get a specific target by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of TargetsResponse</returns>
        System.Threading.Tasks.Task<TargetsResponse> GetTargetAsync (decimal? id, string type);

        /// <summary>
        /// Get a target
        /// </summary>
        /// <remarks>
        /// Get a specific target by type and id
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetTargetAsyncWithHttpInfo (decimal? id, string type);
        /// <summary>
        /// Save a personal favorite
        /// </summary>
        /// <remarks>
        /// Save a personal favorite
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>Task of ApiSuccessResponse</returns>
        System.Threading.Tasks.Task<ApiSuccessResponse> SavePersonalFavoriteAsync (PersonalFavoriteData personalFavoriteData);

        /// <summary>
        /// Save a personal favorite
        /// </summary>
        /// <remarks>
        /// Save a personal favorite
        /// </remarks>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> SavePersonalFavoriteAsyncWithHttpInfo (PersonalFavoriteData personalFavoriteData);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TargetsApi : ITargetsApi
    {
        private Genesys.Workspace.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TargetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TargetsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Genesys.Workspace.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TargetsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TargetsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Genesys.Workspace.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Genesys.Workspace.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Ack the missed calls in recent target Ack the missed calls in recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiSuccessResponse</returns>
        public ApiSuccessResponse AckRecentMissedCalls ()
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = AckRecentMissedCallsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Ack the missed calls in recent target Ack the missed calls in recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        public ApiResponse< ApiSuccessResponse > AckRecentMissedCallsWithHttpInfo ()
        {

            var localVarPath = "/targets/recents/ack-missed-calls";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AckRecentMissedCalls", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// Ack the missed calls in recent target Ack the missed calls in recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiSuccessResponse</returns>
        public async System.Threading.Tasks.Task<ApiSuccessResponse> AckRecentMissedCallsAsync ()
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = await AckRecentMissedCallsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Ack the missed calls in recent target Ack the missed calls in recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> AckRecentMissedCallsAsyncWithHttpInfo ()
        {

            var localVarPath = "/targets/recents/ack-missed-calls";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AckRecentMissedCalls", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// Add a recent target Add a recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>ApiSuccessResponse</returns>
        public ApiSuccessResponse AddRecentTarget (RecentTargetData recentTargetData)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = AddRecentTargetWithHttpInfo(recentTargetData);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add a recent target Add a recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        public ApiResponse< ApiSuccessResponse > AddRecentTargetWithHttpInfo (RecentTargetData recentTargetData)
        {
            // verify the required parameter 'recentTargetData' is set
            if (recentTargetData == null)
                throw new ApiException(400, "Missing required parameter 'recentTargetData' when calling TargetsApi->AddRecentTarget");

            var localVarPath = "/targets/recents/add";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (recentTargetData != null && recentTargetData.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(recentTargetData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = recentTargetData; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddRecentTarget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// Add a recent target Add a recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>Task of ApiSuccessResponse</returns>
        public async System.Threading.Tasks.Task<ApiSuccessResponse> AddRecentTargetAsync (RecentTargetData recentTargetData)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = await AddRecentTargetAsyncWithHttpInfo(recentTargetData);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add a recent target Add a recent target
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="recentTargetData"></param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> AddRecentTargetAsyncWithHttpInfo (RecentTargetData recentTargetData)
        {
            // verify the required parameter 'recentTargetData' is set
            if (recentTargetData == null)
                throw new ApiException(400, "Missing required parameter 'recentTargetData' when calling TargetsApi->AddRecentTarget");

            var localVarPath = "/targets/recents/add";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (recentTargetData != null && recentTargetData.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(recentTargetData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = recentTargetData; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddRecentTarget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// delete a personal favorite delete a personal favorite by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiSuccessResponse</returns>
        public ApiSuccessResponse DeletePersonalFavorite (string id, string type)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = DeletePersonalFavoriteWithHttpInfo(id, type);
             return localVarResponse.Data;
        }

        /// <summary>
        /// delete a personal favorite delete a personal favorite by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        public ApiResponse< ApiSuccessResponse > DeletePersonalFavoriteWithHttpInfo (string id, string type)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TargetsApi->DeletePersonalFavorite");
            // verify the required parameter 'type' is set
            if (type == null)
                throw new ApiException(400, "Missing required parameter 'type' when calling TargetsApi->DeletePersonalFavorite");

            var localVarPath = "/targets/personal-favorites/delete/{type}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (type != null) localVarPathParams.Add("type", Configuration.ApiClient.ParameterToString(type)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeletePersonalFavorite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// delete a personal favorite delete a personal favorite by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiSuccessResponse</returns>
        public async System.Threading.Tasks.Task<ApiSuccessResponse> DeletePersonalFavoriteAsync (string id, string type)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = await DeletePersonalFavoriteAsyncWithHttpInfo(id, type);
             return localVarResponse.Data;

        }

        /// <summary>
        /// delete a personal favorite delete a personal favorite by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> DeletePersonalFavoriteAsyncWithHttpInfo (string id, string type)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TargetsApi->DeletePersonalFavorite");
            // verify the required parameter 'type' is set
            if (type == null)
                throw new ApiException(400, "Missing required parameter 'type' when calling TargetsApi->DeletePersonalFavorite");

            var localVarPath = "/targets/personal-favorites/delete/{type}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (type != null) localVarPathParams.Add("type", Configuration.ApiClient.ParameterToString(type)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeletePersonalFavorite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// Search for targets Search for targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>TargetsResponse</returns>
        public TargetsResponse Get (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = GetWithHttpInfo(searchTerm, filterName, types, excludeGroup, excludeFromGroup, restrictToGroup, sort, limit, matchType);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search for targets Search for targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        public ApiResponse< TargetsResponse > GetWithHttpInfo (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null)
        {
            // verify the required parameter 'searchTerm' is set
            if (searchTerm == null)
                throw new ApiException(400, "Missing required parameter 'searchTerm' when calling TargetsApi->Get");

            var localVarPath = "/targets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (searchTerm != null) localVarQueryParams.Add("searchTerm", Configuration.ApiClient.ParameterToString(searchTerm)); // query parameter
            if (filterName != null) localVarQueryParams.Add("filterName", Configuration.ApiClient.ParameterToString(filterName)); // query parameter
            if (types != null) localVarQueryParams.Add("types", Configuration.ApiClient.ParameterToString(types)); // query parameter
            if (excludeGroup != null) localVarQueryParams.Add("excludeGroup", Configuration.ApiClient.ParameterToString(excludeGroup)); // query parameter
            if (excludeFromGroup != null) localVarQueryParams.Add("excludeFromGroup", Configuration.ApiClient.ParameterToString(excludeFromGroup)); // query parameter
            if (restrictToGroup != null) localVarQueryParams.Add("restrictToGroup", Configuration.ApiClient.ParameterToString(restrictToGroup)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", Configuration.ApiClient.ParameterToString(sort)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (matchType != null) localVarQueryParams.Add("matchType", Configuration.ApiClient.ParameterToString(matchType)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Search for targets Search for targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        public async System.Threading.Tasks.Task<TargetsResponse> GetAsync (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = await GetAsyncWithHttpInfo(searchTerm, filterName, types, excludeGroup, excludeFromGroup, restrictToGroup, sort, limit, matchType);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search for targets Search for targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The text to search for</param>
        /// <param name="filterName">The filter to specify on which fields the search is applied (optional)</param>
        /// <param name="types">Comma separated list of types to include in the search. Valid values are acd-queue, agent-group, agent, route-point, skill and custom-contact. (optional)</param>
        /// <param name="excludeGroup">Comma separated list of types of groups to exclude agent groups from search. Valid values are any agent group names. (optional)</param>
        /// <param name="excludeFromGroup">Comma separated list of types of groups to exclude agents from search. Valid values are any agent group names. (optional)</param>
        /// <param name="restrictToGroup">Comma separated list of groups to limit the search of agents from. Valid values are any agent group names. (optional)</param>
        /// <param name="sort">Desired sort order (asc or desc). asc if not specified (optional)</param>
        /// <param name="limit">Number of results. 100 if not specified. (optional)</param>
        /// <param name="matchType">Type of behavior for the field matching (exact for exact match search). (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetAsyncWithHttpInfo (string searchTerm, string filterName = null, string types = null, string excludeGroup = null, string excludeFromGroup = null, string restrictToGroup = null, string sort = null, decimal? limit = null, string matchType = null)
        {
            // verify the required parameter 'searchTerm' is set
            if (searchTerm == null)
                throw new ApiException(400, "Missing required parameter 'searchTerm' when calling TargetsApi->Get");

            var localVarPath = "/targets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (searchTerm != null) localVarQueryParams.Add("searchTerm", Configuration.ApiClient.ParameterToString(searchTerm)); // query parameter
            if (filterName != null) localVarQueryParams.Add("filterName", Configuration.ApiClient.ParameterToString(filterName)); // query parameter
            if (types != null) localVarQueryParams.Add("types", Configuration.ApiClient.ParameterToString(types)); // query parameter
            if (excludeGroup != null) localVarQueryParams.Add("excludeGroup", Configuration.ApiClient.ParameterToString(excludeGroup)); // query parameter
            if (excludeFromGroup != null) localVarQueryParams.Add("excludeFromGroup", Configuration.ApiClient.ParameterToString(excludeFromGroup)); // query parameter
            if (restrictToGroup != null) localVarQueryParams.Add("restrictToGroup", Configuration.ApiClient.ParameterToString(restrictToGroup)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", Configuration.ApiClient.ParameterToString(sort)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (matchType != null) localVarQueryParams.Add("matchType", Configuration.ApiClient.ParameterToString(matchType)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get personal favorites Get personal favorites
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>TargetsResponse</returns>
        public TargetsResponse GetPersonalFavorites (decimal? limit = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = GetPersonalFavoritesWithHttpInfo(limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get personal favorites Get personal favorites
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        public ApiResponse< TargetsResponse > GetPersonalFavoritesWithHttpInfo (decimal? limit = null)
        {

            var localVarPath = "/targets/personal-favorites";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPersonalFavorites", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get personal favorites Get personal favorites
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        public async System.Threading.Tasks.Task<TargetsResponse> GetPersonalFavoritesAsync (decimal? limit = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = await GetPersonalFavoritesAsyncWithHttpInfo(limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get personal favorites Get personal favorites
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetPersonalFavoritesAsyncWithHttpInfo (decimal? limit = null)
        {

            var localVarPath = "/targets/personal-favorites";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPersonalFavorites", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get recent targets Get recent targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>TargetsResponse</returns>
        public TargetsResponse GetRecentTargets (decimal? limit = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = GetRecentTargetsWithHttpInfo(limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get recent targets Get recent targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        public ApiResponse< TargetsResponse > GetRecentTargetsWithHttpInfo (decimal? limit = null)
        {

            var localVarPath = "/targets/recents";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetRecentTargets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get recent targets Get recent targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of TargetsResponse</returns>
        public async System.Threading.Tasks.Task<TargetsResponse> GetRecentTargetsAsync (decimal? limit = null)
        {
             ApiResponse<TargetsResponse> localVarResponse = await GetRecentTargetsAsyncWithHttpInfo(limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get recent targets Get recent targets
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results. 50 if not specified. (optional)</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetRecentTargetsAsyncWithHttpInfo (decimal? limit = null)
        {

            var localVarPath = "/targets/recents";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetRecentTargets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get a target Get a specific target by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>TargetsResponse</returns>
        public TargetsResponse GetTarget (decimal? id, string type)
        {
             ApiResponse<TargetsResponse> localVarResponse = GetTargetWithHttpInfo(id, type);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a target Get a specific target by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>ApiResponse of TargetsResponse</returns>
        public ApiResponse< TargetsResponse > GetTargetWithHttpInfo (decimal? id, string type)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TargetsApi->GetTarget");
            // verify the required parameter 'type' is set
            if (type == null)
                throw new ApiException(400, "Missing required parameter 'type' when calling TargetsApi->GetTarget");

            var localVarPath = "/targets/{type}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (type != null) localVarPathParams.Add("type", Configuration.ApiClient.ParameterToString(type)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTarget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Get a target Get a specific target by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of TargetsResponse</returns>
        public async System.Threading.Tasks.Task<TargetsResponse> GetTargetAsync (decimal? id, string type)
        {
             ApiResponse<TargetsResponse> localVarResponse = await GetTargetAsyncWithHttpInfo(id, type);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a target Get a specific target by type and id
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the target</param>
        /// <param name="type">the type of the target</param>
        /// <returns>Task of ApiResponse (TargetsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TargetsResponse>> GetTargetAsyncWithHttpInfo (decimal? id, string type)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TargetsApi->GetTarget");
            // verify the required parameter 'type' is set
            if (type == null)
                throw new ApiException(400, "Missing required parameter 'type' when calling TargetsApi->GetTarget");

            var localVarPath = "/targets/{type}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (type != null) localVarPathParams.Add("type", Configuration.ApiClient.ParameterToString(type)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTarget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TargetsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TargetsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TargetsResponse)));
        }

        /// <summary>
        /// Save a personal favorite Save a personal favorite
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>ApiSuccessResponse</returns>
        public ApiSuccessResponse SavePersonalFavorite (PersonalFavoriteData personalFavoriteData)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = SavePersonalFavoriteWithHttpInfo(personalFavoriteData);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Save a personal favorite Save a personal favorite
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>ApiResponse of ApiSuccessResponse</returns>
        public ApiResponse< ApiSuccessResponse > SavePersonalFavoriteWithHttpInfo (PersonalFavoriteData personalFavoriteData)
        {
            // verify the required parameter 'personalFavoriteData' is set
            if (personalFavoriteData == null)
                throw new ApiException(400, "Missing required parameter 'personalFavoriteData' when calling TargetsApi->SavePersonalFavorite");

            var localVarPath = "/targets/personal-favorites/save";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (personalFavoriteData != null && personalFavoriteData.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(personalFavoriteData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = personalFavoriteData; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SavePersonalFavorite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

        /// <summary>
        /// Save a personal favorite Save a personal favorite
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>Task of ApiSuccessResponse</returns>
        public async System.Threading.Tasks.Task<ApiSuccessResponse> SavePersonalFavoriteAsync (PersonalFavoriteData personalFavoriteData)
        {
             ApiResponse<ApiSuccessResponse> localVarResponse = await SavePersonalFavoriteAsyncWithHttpInfo(personalFavoriteData);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Save a personal favorite Save a personal favorite
        /// </summary>
        /// <exception cref="Genesys.Workspace.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personalFavoriteData"></param>
        /// <returns>Task of ApiResponse (ApiSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiSuccessResponse>> SavePersonalFavoriteAsyncWithHttpInfo (PersonalFavoriteData personalFavoriteData)
        {
            // verify the required parameter 'personalFavoriteData' is set
            if (personalFavoriteData == null)
                throw new ApiException(400, "Missing required parameter 'personalFavoriteData' when calling TargetsApi->SavePersonalFavorite");

            var localVarPath = "/targets/personal-favorites/save";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (personalFavoriteData != null && personalFavoriteData.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(personalFavoriteData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = personalFavoriteData; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SavePersonalFavorite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiSuccessResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiSuccessResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiSuccessResponse)));
        }

    }
}
